LOG_ERROR="${LOG_ERROR:-${LIGHT_RED}!!! }"
LOG_NOTICE="${LOG_NOTICE:-${WHITE}::: }"
LOG_WARNING="${LOG_WARNING:-$BROWN}"
LOG_SUCCESS="${LOG_SUCCESS:-$LIGHT_GREEN}"
LOG_STATUS="${LOG_STATUS:-${LIGHT_GREEN}===> ${WHITE}}"
LOG_RESET="${LOG_RESET:-$NC}"

export LOG_ERROR LOG_NOTICE LOG_WARNING LOG_SUCCESS LOG_RESET

